### ISSUE TITLE
Unexpected value 'LongPressModule'

### ISSUE THREAD

**Issue by leonardoespinosa** [wbhob/ionic-long-press#10]
Hi, 

I try import ionic-long-press in my project but when ionic start i found the following error:

`Error: Unexpected value 'LongPressModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

Can you help me? This is my app.module.ts:

```
.....
@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    HttpClientModule,
    LongPressModule
  ],
......
```

This is my package.json:

```
"name": "ionic",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/animations": "5.2.10",
        "@angular/common": "5.2.10",
        "@angular/compiler": "5.2.10",
        "@angular/compiler-cli": "5.2.10",
        "@angular/core": "5.2.10",
        "@angular/forms": "5.2.10",
        "@angular/http": "5.2.10",
        "@angular/platform-browser": "5.2.10",
        "@angular/platform-browser-dynamic": "5.2.10",
        "@ionic-native/camera": "^4.7.0",
        "@ionic-native/core": "4.7.0",
        "@ionic-native/device": "4.7.0",
        "@ionic-native/file": "4.7.0",
        "@ionic-native/file-transfer": "^4.7.0",
        "@ionic-native/media": "4.7.0",
        "@ionic-native/network": "4.7.0",
        "@ionic-native/splash-screen": "4.7.0",
        "@ionic-native/status-bar": "4.7.0",
        "@ionic/storage": "2.1.3",
        "cordova-android": "6.2.3",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-compat": "1.2.0",
        "cordova-plugin-device": "2.0.2",
        "cordova-plugin-file": "4.3.3",
        "cordova-plugin-file-transfer": "^1.7.1",
        "cordova-plugin-ionic-keyboard": "2.0.5",
        "cordova-plugin-ionic-webview": "1.1.19",
        "cordova-plugin-media": "3.0.1",
        "cordova-plugin-network-information": "2.0.1",
        "cordova-plugin-splashscreen": "5.0.2",
        "cordova-plugin-statusbar": "2.4.2",
        "cordova-plugin-whitelist": "1.3.3",
        "font-awesome": "4.7.0",
        "ionic-angular": "3.9.2",
        "ionic-long-press": "^1.4.0",
        "ionicons": "3.0.0",
        "ng2-dragula": "1.5.0",
        "rxjs": "5.5.11",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.26"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.9",
        "typescript": "~2.6.2"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-device": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-file": {},
            "cordova-plugin-ionic-keyboard": {},
            "cordova-plugin-ionic-webview": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-media": {}
        },
        "platforms": [
            "android"
        ]
    },
    "config": {
        "ionic_copy": "./scripts/copy.config.js"
    }
}
```

thanks, regards!

**Comment by Lechevallier** [comment]
I have the same problem since yesterday, don't know how to fix it...

**Comment by wbhob** [comment]
I think I know what this issue is, can you give me a stack trace please

**Comment by wbhob** [comment]
Also are you building with --prod?

**Comment by Lechevallier** [comment]
I'm not building with --prod.
My stack trace:
```
Error: Unexpected value 'LongPressModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:8100/build/vendor.js:81634:34)
    at http://localhost:8100/build/vendor.js:95487:44
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/vendor.js:95470:49)
    at JitCompiler._loadModules (http://localhost:8100/build/vendor.js:106905:70)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:106878:36)
    at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:106807:37)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8100/build/vendor.js:4845:25)
    at PlatformRef_.bootstrapModule (http://localhost:8100/build/vendor.js:4831:21)
    at Object.234 (http://localhost:8100/build/main.js:938:109)`
```

**Comment by wbhob** [comment]
I've pushed a new version packaged with ng-packagr (v1.5.0). That should fix your problem; can you try it and report back please?

**Comment by Lechevallier** [comment]
Perfect ! It's working :)
@leonardoespinosa just change to `"ionic-long-press": "^1.5.0"` in your package.json and rerun `npm install`

**Comment by leonardoespinosa** [comment]
@Lechevallier @wbhob Perfect! Thank you very much!!
